### ISSUE TITLE
sensor.hacs unavailable

### ISSUE THREAD

**Issue by AndyVRD** [krpn/home-assistant-updates-notification#3]
Hi,

Is there anything changed that causes the sensor.hacs become unavailable? I no longer receive push notifications if there is a new hacs version available or a new hacs frontend/integration update. :)

```
      updater_hacs:
        friendly_name: HACS Integrations
        device_class: problem
        value_template: "{{ states('sensor.hacs')|int(0) != 0 }}"
        attribute_templates:
          repositories: "{{ state_attr('sensor.hacs', 'repositories') }}"
```
